/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import com.fazecast.jSerialComm.*;
import comunicacion.Comunicacion;

/**
 *
 * @author admin
 */
public class IComunicacion extends javax.swing.JFrame {

    /**
     * Creates new form Comunicacion
     */
    private Comunicacion comu;

    public IComunicacion() {
        initComponents();
        CB_Entrada.removeAllItems();
        CB_Salida.removeAllItems();
        for (String puerto : this.listaPuertos()) {
            CB_Entrada.addItem(puerto);
            CB_Salida.addItem(puerto);
        }
        
         this.Btn_Iniciarjuego.setEnabled(false);
         this.Btn_EnviarB.setEnabled(false);
         this.Btn_EnviarC.setEnabled(false);
         this.Btn_EnviarD.setEnabled(false);
         this.Btn_EnviarA1.setEnabled(false);
         
    }

    public static ArrayList<String> listaPuertos() {
        ArrayList<String> puertos = new ArrayList<String>();
        SerialPort[] comPort = SerialPort.getCommPorts();
        for (int i = 0; i < comPort.length; i++) {
            puertos.add(comPort[i].getSystemPortName());
        }
        return puertos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Entrada = new javax.swing.JComboBox<String>();
        BtnConectar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CB_Salida = new javax.swing.JComboBox<String>();
        Btn_EnviarD = new javax.swing.JButton();
        Btn_Iniciarjuego = new javax.swing.JButton();
        Btn_EnviarC = new javax.swing.JButton();
        Btn_EnviarB = new javax.swing.JButton();
        Btn_EnviarA1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(627, 427));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EntradaActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 142, -1));

        BtnConectar.setText("CONECTAR");
        BtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel3.setText("PUERTOS SALIDA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel4.setText("PUERTOS ENTRADA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, 20));

        CB_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 142, -1));

        Btn_EnviarD.setText("JUGADOR D");
        Btn_EnviarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarDActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_EnviarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        Btn_Iniciarjuego.setText("Iniciar juego");
        Btn_Iniciarjuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarjuegoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Iniciarjuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        Btn_EnviarC.setText("JUGADOR C");
        Btn_EnviarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarCActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_EnviarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        Btn_EnviarB.setText("JUGADOR B");
        Btn_EnviarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarBActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_EnviarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        Btn_EnviarA1.setText("JUGADOR A");
        Btn_EnviarA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarA1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_EnviarA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EntradaActionPerformed

    private void CB_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_SalidaActionPerformed

    private void BtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConectarActionPerformed
        // TODO add your handling code here:
        this.comu = new Comunicacion(this.CB_Entrada.getSelectedIndex(), this.CB_Salida.getSelectedIndex());
        this.comu.Escuchar();

         this.Btn_EnviarB.setEnabled(true);
         this.Btn_EnviarC.setEnabled(true);
         this.Btn_EnviarD.setEnabled(true);
         this.Btn_EnviarA1.setEnabled(true);
         
        
    }//GEN-LAST:event_BtnConectarActionPerformed

    private void Btn_EnviarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarDActionPerformed
        // TODO add your handling code here:
        this.comu.setEstacion("00000011");
         this.Btn_EnviarA1.setEnabled(false);
           this.Btn_EnviarC.setEnabled(false);
            this.Btn_EnviarB.setEnabled(false);
            this.Btn_Iniciarjuego.setEnabled(false);
        //this.comu.Escribir();
      
    }//GEN-LAST:event_Btn_EnviarDActionPerformed

    private void Btn_IniciarjuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarjuegoActionPerformed
        // TODO add your handling code here:
    
           this.comu.Escribir();
      
       // }while (comu.participantes()== false);    

    }//GEN-LAST:event_Btn_IniciarjuegoActionPerformed

    private void Btn_EnviarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarCActionPerformed
        // TODO add your handling code here:
        this.comu.setEstacion("00000010");
         this.Btn_EnviarA1.setEnabled(false);
           this.Btn_EnviarB.setEnabled(false);
            this.Btn_EnviarD.setEnabled(false);
            this.Btn_Iniciarjuego.setEnabled(false);
        
    }//GEN-LAST:event_Btn_EnviarCActionPerformed

    private void Btn_EnviarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarBActionPerformed
        // TODO add your handling code here:
         this.comu.setEstacion("00000001");
          this.Btn_EnviarA1.setEnabled(false);
           this.Btn_EnviarC.setEnabled(false);
            this.Btn_EnviarD.setEnabled(false);
            this.Btn_Iniciarjuego.setEnabled(false);
    }//GEN-LAST:event_Btn_EnviarBActionPerformed

    private void Btn_EnviarA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarA1ActionPerformed
        // TODO add your handling code here:
         this.comu.setEstacion("00000000");
          this.Btn_EnviarB.setEnabled(false);
           this.Btn_EnviarC.setEnabled(false);
            this.Btn_EnviarD.setEnabled(false);
             this.Btn_Iniciarjuego.setEnabled(true);
            
         
    }//GEN-LAST:event_Btn_EnviarA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IComunicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConectar;
    private javax.swing.JButton Btn_EnviarA1;
    private javax.swing.JButton Btn_EnviarB;
    private javax.swing.JButton Btn_EnviarC;
    private javax.swing.JButton Btn_EnviarD;
    private javax.swing.JButton Btn_Iniciarjuego;
    private javax.swing.JComboBox<String> CB_Entrada;
    private javax.swing.JComboBox<String> CB_Salida;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
