/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.util.ArrayList;
import com.fazecast.jSerialComm.*;
import comunicacion.Comunicacion;

/**
 *
 * @author admin
 */
public class IComunicacion extends javax.swing.JFrame {

    /**
     * Creates new form Comunicacion
     */
    private Comunicacion comu;

    public IComunicacion() {
        initComponents();
        CB_Entrada.removeAllItems();
        CB_Salida.removeAllItems();
        for (String puerto : this.listaPuertos()) {
            CB_Entrada.addItem(puerto);
            CB_Salida.addItem(puerto);
        }
        
         this.Btn_Enviar.setEnabled(false);
    }

    public static ArrayList<String> listaPuertos() {
        ArrayList<String> puertos = new ArrayList<String>();
        SerialPort[] comPort = SerialPort.getCommPorts();
        for (int i = 0; i < comPort.length; i++) {
            puertos.add(comPort[i].getSystemPortName());
        }
        return puertos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CB_Entrada = new javax.swing.JComboBox<>();
        TF_Enviar = new javax.swing.JTextField();
        TF_Recibido = new javax.swing.JTextField();
        Btn_Enviar = new javax.swing.JButton();
        BtnConectar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CB_Salida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(627, 427));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DATOS A ENVIAR:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        CB_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_EntradaActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 142, -1));

        TF_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 372, -1));
        getContentPane().add(TF_Recibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 372, -1));

        Btn_Enviar.setText("ENVIAR");
        Btn_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        BtnConectar.setText("CONECTAR");
        BtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel2.setText("DATOS RECIBIDOS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel3.setText("PUERTOS SALIDA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel4.setText("PUERTOS ENTRADA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, 20));

        CB_Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SalidaActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 142, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_EnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_EnviarActionPerformed

    private void Btn_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnviarActionPerformed
        this.comu.Escribir();
        

    }//GEN-LAST:event_Btn_EnviarActionPerformed

    private void CB_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_EntradaActionPerformed

    private void CB_SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_SalidaActionPerformed

    private void BtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConectarActionPerformed
        // TODO add your handling code here:
        this.comu = new Comunicacion(this.CB_Entrada.getSelectedIndex(), this.CB_Salida.getSelectedIndex());
        this.comu.Escuchar();
        this.Btn_Enviar.setEnabled(true);
    }//GEN-LAST:event_BtnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IComunicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IComunicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConectar;
    private javax.swing.JButton Btn_Enviar;
    private javax.swing.JComboBox<String> CB_Entrada;
    private javax.swing.JComboBox<String> CB_Salida;
    private javax.swing.JTextField TF_Enviar;
    private javax.swing.JTextField TF_Recibido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
